# Generated by Django 6.0.3 on 2026-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='distance',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='train',
            name='price_per_km',
            field=models.FloatField(default=2.0),
        ),
    ]
