# Generated by Django 6.0.3 on 2026-05-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_train_distance_train_price_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
