# Generated by Django 6.0.3 on 2026-05-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='coach',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='distance',
            field=models.IntegerField(default=1000),
        ),
    ]
